# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e74b88572bfb965e33a225cc296292d48a89e2c77da0cf0483a95d505800465329784e5f54314d96e03d4ce0a1484b71b3b7ce6e46ca260e2a0a87b85970e154

test:
  secret_key_base: 7a1454e1fa9817279f210b0a1cb1171582c2cdabb2edd6dab4f8378582d6152bff4a8271aec8897debe613d5d49d71205a894cf8e4c338f86f49db9f7b7b31eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
